---
kind: pipeline
type: kubernetes
name: build-test-deploy

platform:
  os: linux
  arch: amd64


steps:
  - name: feature-docker-tag-review
    image: alpine
    privileged: false
    commands:
    - echo -n "${DRONE_SOURCE_BRANCH##feature/}" | tr '[:upper:]' '[:lower:]' > .tags
    when:
      branch:
      - feature/*

  - name: feat-docker-tag-review
    image: alpine
    privileged: false
    commands:
    - echo -n "${DRONE_SOURCE_BRANCH##feat/}" | tr '[:upper:]' '[:lower:]' > .tags
    when:
      branch:
      - feat/*

  - name: docker-tag-staging
    image: alpine
    privileged: false
    commands:
    - echo -n "${DRONE_BRANCH,,},staging,latest" > .tags
    when:
      branch:
      - develop

  - name: docker-image-build
    image: plugins/docker
    privileged: false
    settings:
      username:
        from_secret: DOCKER_USERNAME
      password:
        from_secret: DOCKER_PASSWORD
      registry: registry.vepay.cf
      repo: registry.vepay.cf/${DRONE_REPO,,}
    when:
      branch:
      - feature/*
      - feat/*
      - develop

trigger:
  event:
    include:
      - pull_request
      - push
  branch:
    - feature/*
    - feat/*
    - develop
---
kind: signature
hmac: 414301d12459c61f7ca45b029897509a7545604808923ef6ae47a7173c4b6593

...
