version: "3.6"

services:
  api_init:
    image: alpine
    entrypoint: /bin/sh -c "chown -Rhv 33:33 /www/runtime && chmod -v 755 /www/runtime"
    restart: "no"
    volumes:
      - runtime:/www/runtime

  api:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
      args:
        ENVIRONMENT: dev
    image: api
    user: www-data
    volumes:
      - ./:/www/
      - runtime:/www/runtime
    environment:
      TZ: Europe/Moscow
      DATABASE_DSN: "mysql:host=mariadb;port=3306;dbname=vepay"
      DATABASE_USER: vepay
      DATABASE_USER_PASSWORD: vepay
      TEST_URL: "http://localhost:8000"
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_DB_NUM_QUEUE: 3
      REDIS_DB_NUM_CACHE: 4
      COMPOSER_HOME: /tmp
      XDEBUG_CONFIG: >-
        remote_enable=${XDEBUG_REMOTE_ENABLE:-1}
        remote_connect_back=${XDEBUG_REMOTE_CONNECT_BACK:-1}
        discover_client_host=${XDEBUG_DISCOVER_CLIENT_HOST:-1}
        client_host=${XDEBUG_CLIENT_HOST:-""}
        client_port=${XDEBUG_CLIENT_PORT:-9000}
        idekey=${XDEBUG_IDEKEY:-PHPSTORM}
    ports:
      - "8000:8000/tcp"
    depends_on:
      - api_init
      - mariadb
      - redis
    cap_drop:
      - ALL

  mariadb:
    image: mariadb:10.4
    volumes:
      - mariadb_volume:/var/lib/mysql
      - ./dump/:/docker-entrypoint-initdb.d/
    ports:
      - "3306"
    environment:
      TZ: Europe/Moscow
      MYSQL_DATABASE: vepay
      MYSQL_USER: vepay
      MYSQL_PASSWORD: vepay
      MYSQL_RANDOM_ROOT_PASSWORD: "true"

  redis:
    image: redis:6
    entrypoint: redis-server --appendonly yes
    environment:
      TZ: Europe/Moscow
    ports:
      - "6379"

volumes:
  mariadb_volume: { }
  runtime: { }
