#!/usr/bin/env php
<?php
/**
 * Yii Application Initialization Tool
 *
 * In order to run in non-interactive mode:
 *
 * init --env=prod
 */

if (!extension_loaded('openssl')) {
    die('The OpenSSL PHP extension is required by Yii2.');
}

$params = getParams();
$root = str_replace('\\', '/', __DIR__);

if (isset($params['env']) && !empty($params['env'])) {
    $mode = $params['env'];
    if ($mode == "prod") {
        echo "init: prod\n";
        copy($root . "/config/prod/index.php", $root . "/web/index.php");
        if (!file_exists($root . "/config/params.php")) {
			copy($root . "/config/prod/params.php", $root . "/config/params.php");
		}
        if (!file_exists($root . "/config/db.php")) {
            copy($root . "/config/prod/db.php", $root . "/config/db.php");
        }
        if (!file_exists($root . "/config/log.php")) {
            copy($root . "/config/prod/log.php", $root . "/config/log.php");
        }
    } else {
        $source_dir_path = $root . sprintf("/config/%s/", $mode);
        if (!file_exists($source_dir_path)) {
            throw new RuntimeException(sprintf("Directory must exists `%s`.", $source_dir_path));
        }
        echo sprintf("init: %s\n", $mode);
        copy($source_dir_path . "index.php", $root . "/web/index.php");
        copy($source_dir_path . "params.php", $root . "/config/params.php");
        copy($source_dir_path . "db.php", $root . "/config/db.php");
        copy($source_dir_path . "log.php", $root . "/config/log.php");
        copy($source_dir_path . "test_params.php", $root . "/config/test_params.php");
    }
} else {
    echo "Run: ./init --env={dev,test,kube,prod}\n";
}

function getParams()
{
    $rawParams = [];
    if (isset($_SERVER['argv'])) {
        $rawParams = $_SERVER['argv'];
        array_shift($rawParams);
    }

    $params = [];
    foreach ($rawParams as $param) {
        if (preg_match('/^--([\w-]*\w)(=(.*))?$/', $param, $matches)) {
            $name = $matches[1];
            $params[$name] = isset($matches[3]) ? $matches[3] : true;
        } else {
            $params[] = $param;
        }
    }
    return $params;
}
