<?php

use yii\db\Migration;

/**
 * Class m210804_155837_country
 */
class m210804_155837_country extends Migration
{
    /**
     * {@inheritDoc}
     */
    public function safeUp()
    {
        $tableOptions = 'CHARACTER SET utf8 COLLATE utf8_general_ci ENGINE=InnoDB';
        $this->createTable('country', [
            'Id' => $this->integer(),
            'Alpha2' => $this->char(2)->notNull(),
            'Alpha3' => $this->char(3)->notNull(),
            'En' => $this->char(64)->notNull(),
            'Ru' => $this->char(64)->notNull(),
        ], $tableOptions);
        $this->addPrimaryKey('country_pk', 'country', 'Id');

        $this->batchInsert('country', ['Id', 'Alpha2', 'Alpha3', 'En', 'Ru'], $this->data());
    }

    /**
     * {@inheritDoc}
     */
    public function safeDown()
    {
        $this->dropTable('country');
    }

    private function data(): array
    {
        return [
            [
                'Id' => 4,
                'Alpha2' => 'AF',
                'Alpha3' => 'AFG',
                'En' => 'Afghanistan',
                'Ru' => 'Афганистан',
            ],
            [
                'Id' => 8,
                'Alpha2' => 'AL',
                'Alpha3' => 'ALB',
                'En' => 'Albania',
                'Ru' => 'Албания',
            ],
            [
                'Id' => 12,
                'Alpha2' => 'DZ',
                'Alpha3' => 'DZA',
                'En' => 'Algeria',
                'Ru' => 'Алжир',
            ],
            [
                'Id' => 20,
                'Alpha2' => 'AD',
                'Alpha3' => 'AND',
                'En' => 'Andorra',
                'Ru' => 'Андорра',
            ],
            [
                'Id' => 24,
                'Alpha2' => 'AO',
                'Alpha3' => 'AGO',
                'En' => 'Angola',
                'Ru' => 'Ангола',
            ],
            [
                'Id' => 28,
                'Alpha2' => 'AG',
                'Alpha3' => 'ATG',
                'En' => 'Antigua and Barbuda',
                'Ru' => 'Антигуа и Барбуда',
            ],
            [
                'Id' => 32,
                'Alpha2' => 'AR',
                'Alpha3' => 'ARG',
                'En' => 'Argentina',
                'Ru' => 'Аргентина',
            ],
            [
                'Id' => 51,
                'Alpha2' => 'AM',
                'Alpha3' => 'ARM',
                'En' => 'Armenia',
                'Ru' => 'Армения',
            ],
            [
                'Id' => 36,
                'Alpha2' => 'AU',
                'Alpha3' => 'AUS',
                'En' => 'Australia',
                'Ru' => 'Австралия',
            ],
            [
                'Id' => 40,
                'Alpha2' => 'AT',
                'Alpha3' => 'AUT',
                'En' => 'Austria',
                'Ru' => 'Австрия',
            ],
            [
                'Id' => 31,
                'Alpha2' => 'AZ',
                'Alpha3' => 'AZE',
                'En' => 'Azerbaijan',
                'Ru' => 'Азербайджан',
            ],
            [
                'Id' => 44,
                'Alpha2' => 'BS',
                'Alpha3' => 'BHS',
                'En' => 'Bahamas',
                'Ru' => 'Багамские Острова',
            ],
            [
                'Id' => 48,
                'Alpha2' => 'BH',
                'Alpha3' => 'BHR',
                'En' => 'Bahrain',
                'Ru' => 'Бахрейн',
            ],
            [
                'Id' => 50,
                'Alpha2' => 'BD',
                'Alpha3' => 'BGD',
                'En' => 'Bangladesh',
                'Ru' => 'Бангладеш',
            ],
            [
                'Id' => 52,
                'Alpha2' => 'BB',
                'Alpha3' => 'BRB',
                'En' => 'Barbados',
                'Ru' => 'Барбадос',
            ],
            [
                'Id' => 112,
                'Alpha2' => 'BY',
                'Alpha3' => 'BLR',
                'En' => 'Belarus',
                'Ru' => 'Белоруссия',
            ],
            [
                'Id' => 56,
                'Alpha2' => 'BE',
                'Alpha3' => 'BEL',
                'En' => 'Belgium',
                'Ru' => 'Бельгия',
            ],
            [
                'Id' => 84,
                'Alpha2' => 'BZ',
                'Alpha3' => 'BLZ',
                'En' => 'Belize',
                'Ru' => 'Белиз',
            ],
            [
                'Id' => 204,
                'Alpha2' => 'BJ',
                'Alpha3' => 'BEN',
                'En' => 'Benin',
                'Ru' => 'Бенин',
            ],
            [
                'Id' => 64,
                'Alpha2' => 'BT',
                'Alpha3' => 'BTN',
                'En' => 'Bhutan',
                'Ru' => 'Бутан',
            ],
            [
                'Id' => 68,
                'Alpha2' => 'BO',
                'Alpha3' => 'BOL',
                'En' => 'Bolivia (Plurinational State of]',
                'Ru' => 'Боливия',
            ],
            [
                'Id' => 70,
                'Alpha2' => 'BA',
                'Alpha3' => 'BIH',
                'En' => 'Bosnia and Herzegovina',
                'Ru' => 'Босния и Герцеговина',
            ],
            [
                'Id' => 72,
                'Alpha2' => 'BW',
                'Alpha3' => 'BWA',
                'En' => 'Botswana',
                'Ru' => 'Ботсвана',
            ],
            [
                'Id' => 76,
                'Alpha2' => 'BR',
                'Alpha3' => 'BRA',
                'En' => 'Brazil',
                'Ru' => 'Бразилия',
            ],
            [
                'Id' => 96,
                'Alpha2' => 'BN',
                'Alpha3' => 'BRN',
                'En' => 'Brunei Darussalam',
                'Ru' => 'Бруней',
            ],
            [
                'Id' => 100,
                'Alpha2' => 'BG',
                'Alpha3' => 'BGR',
                'En' => 'Bulgaria',
                'Ru' => 'Болгария',
            ],
            [
                'Id' => 854,
                'Alpha2' => 'BF',
                'Alpha3' => 'BFA',
                'En' => 'Burkina Faso',
                'Ru' => 'Буркина-Фасо',
            ],
            [
                'Id' => 108,
                'Alpha2' => 'BI',
                'Alpha3' => 'BDI',
                'En' => 'Burundi',
                'Ru' => 'Бурунди',
            ],
            [
                'Id' => 132,
                'Alpha2' => 'CV',
                'Alpha3' => 'CPV',
                'En' => 'Cabo Verde',
                'Ru' => 'Кабо-Верде',
            ],
            [
                'Id' => 116,
                'Alpha2' => 'KH',
                'Alpha3' => 'KHM',
                'En' => 'Cambodia',
                'Ru' => 'Камбоджа',
            ],
            [
                'Id' => 120,
                'Alpha2' => 'CM',
                'Alpha3' => 'CMR',
                'En' => 'Cameroon',
                'Ru' => 'Камерун',
            ],
            [
                'Id' => 124,
                'Alpha2' => 'CA',
                'Alpha3' => 'CAN',
                'En' => 'Canada',
                'Ru' => 'Канада',
            ],
            [
                'Id' => 140,
                'Alpha2' => 'CF',
                'Alpha3' => 'CAF',
                'En' => 'Central African Republic',
                'Ru' => 'ЦАР',
            ],
            [
                'Id' => 148,
                'Alpha2' => 'TD',
                'Alpha3' => 'TCD',
                'En' => 'Chad',
                'Ru' => 'Чад',
            ],
            [
                'Id' => 152,
                'Alpha2' => 'CL',
                'Alpha3' => 'CHL',
                'En' => 'Chile',
                'Ru' => 'Чили',
            ],
            [
                'Id' => 156,
                'Alpha2' => 'CN',
                'Alpha3' => 'CHN',
                'En' => 'China',
                'Ru' => 'Китай (Китайская Народная Республика]',
            ],
            [
                'Id' => 170,
                'Alpha2' => 'CO',
                'Alpha3' => 'COL',
                'En' => 'Colombia',
                'Ru' => 'Колумбия',
            ],
            [
                'Id' => 174,
                'Alpha2' => 'KM',
                'Alpha3' => 'COM',
                'En' => 'Comoros',
                'Ru' => 'Коморы',
            ],
            [
                'Id' => 178,
                'Alpha2' => 'CG',
                'Alpha3' => 'COG',
                'En' => 'Congo',
                'Ru' => 'Республика Конго',
            ],
            [
                'Id' => 180,
                'Alpha2' => 'CD',
                'Alpha3' => 'COD',
                'En' => 'Congo, Democratic Republic of the',
                'Ru' => 'ДР Конго',
            ],
            [
                'Id' => 188,
                'Alpha2' => 'CR',
                'Alpha3' => 'CRI',
                'En' => 'Costa Rica',
                'Ru' => 'Коста-Рика',
            ],
            [
                'Id' => 384,
                'Alpha2' => 'CI',
                'Alpha3' => 'CIV',
                'En' => 'Côte d\'Ivoire',
                'Ru' => 'Кот-д’Ивуар',
            ],
            [
                'Id' => 191,
                'Alpha2' => 'HR',
                'Alpha3' => 'HRV',
                'En' => 'Croatia',
                'Ru' => 'Хорватия',
            ],
            [
                'Id' => 192,
                'Alpha2' => 'CU',
                'Alpha3' => 'CUB',
                'En' => 'Cuba',
                'Ru' => 'Куба',
            ],
            [
                'Id' => 196,
                'Alpha2' => 'CY',
                'Alpha3' => 'CYP',
                'En' => 'Cyprus',
                'Ru' => 'Кипр',
            ],
            [
                'Id' => 203,
                'Alpha2' => 'CZ',
                'Alpha3' => 'CZE',
                'En' => 'Czechia',
                'Ru' => 'Чехия',
            ],
            [
                'Id' => 208,
                'Alpha2' => 'DK',
                'Alpha3' => 'DNK',
                'En' => 'Denmark',
                'Ru' => 'Дания',
            ],
            [
                'Id' => 262,
                'Alpha2' => 'DJ',
                'Alpha3' => 'DJI',
                'En' => 'Djibouti',
                'Ru' => 'Джибути',
            ],
            [
                'Id' => 212,
                'Alpha2' => 'DM',
                'Alpha3' => 'DMA',
                'En' => 'Dominica',
                'Ru' => 'Доминика',
            ],
            [
                'Id' => 214,
                'Alpha2' => 'DO',
                'Alpha3' => 'DOM',
                'En' => 'Dominican Republic',
                'Ru' => 'Доминиканская Республика',
            ],
            [
                'Id' => 218,
                'Alpha2' => 'EC',
                'Alpha3' => 'ECU',
                'En' => 'Ecuador',
                'Ru' => 'Эквадор',
            ],
            [
                'Id' => 818,
                'Alpha2' => 'EG',
                'Alpha3' => 'EGY',
                'En' => 'Egypt',
                'Ru' => 'Египет',
            ],
            [
                'Id' => 222,
                'Alpha2' => 'SV',
                'Alpha3' => 'SLV',
                'En' => 'El Salvador',
                'Ru' => 'Сальвадор',
            ],
            [
                'Id' => 226,
                'Alpha2' => 'GQ',
                'Alpha3' => 'GNQ',
                'En' => 'Equatorial Guinea',
                'Ru' => 'Экваториальная Гвинея',
            ],
            [
                'Id' => 232,
                'Alpha2' => 'ER',
                'Alpha3' => 'ERI',
                'En' => 'Eritrea',
                'Ru' => 'Эритрея',
            ],
            [
                'Id' => 233,
                'Alpha2' => 'EE',
                'Alpha3' => 'EST',
                'En' => 'Estonia',
                'Ru' => 'Эстония',
            ],
            [
                'Id' => 748,
                'Alpha2' => 'SZ',
                'Alpha3' => 'SWZ',
                'En' => 'Eswatini',
                'Ru' => 'Эсватини',
            ],
            [
                'Id' => 231,
                'Alpha2' => 'ET',
                'Alpha3' => 'ETH',
                'En' => 'Ethiopia',
                'Ru' => 'Эфиопия',
            ],
            [
                'Id' => 242,
                'Alpha2' => 'FJ',
                'Alpha3' => 'FJI',
                'En' => 'Fiji',
                'Ru' => 'Фиджи',
            ],
            [
                'Id' => 246,
                'Alpha2' => 'FI',
                'Alpha3' => 'FIN',
                'En' => 'Finland',
                'Ru' => 'Финляндия',
            ],
            [
                'Id' => 250,
                'Alpha2' => 'FR',
                'Alpha3' => 'FRA',
                'En' => 'France',
                'Ru' => 'Франция',
            ],
            [
                'Id' => 266,
                'Alpha2' => 'GA',
                'Alpha3' => 'GAB',
                'En' => 'Gabon',
                'Ru' => 'Габон',
            ],
            [
                'Id' => 270,
                'Alpha2' => 'GM',
                'Alpha3' => 'GMB',
                'En' => 'Gambia',
                'Ru' => 'Гамбия',
            ],
            [
                'Id' => 268,
                'Alpha2' => 'GE',
                'Alpha3' => 'GEO',
                'En' => 'Georgia',
                'Ru' => 'Грузия',
            ],
            [
                'Id' => 276,
                'Alpha2' => 'DE',
                'Alpha3' => 'DEU',
                'En' => 'Germany',
                'Ru' => 'Германия',
            ],
            [
                'Id' => 288,
                'Alpha2' => 'GH',
                'Alpha3' => 'GHA',
                'En' => 'Ghana',
                'Ru' => 'Гана',
            ],
            [
                'Id' => 300,
                'Alpha2' => 'GR',
                'Alpha3' => 'GRC',
                'En' => 'Greece',
                'Ru' => 'Греция',
            ],
            [
                'Id' => 308,
                'Alpha2' => 'GD',
                'Alpha3' => 'GRD',
                'En' => 'Grenada',
                'Ru' => 'Гренада',
            ],
            [
                'Id' => 320,
                'Alpha2' => 'GT',
                'Alpha3' => 'GTM',
                'En' => 'Guatemala',
                'Ru' => 'Гватемала',
            ],
            [
                'Id' => 324,
                'Alpha2' => 'GN',
                'Alpha3' => 'GIN',
                'En' => 'Guinea',
                'Ru' => 'Гвинея',
            ],
            [
                'Id' => 624,
                'Alpha2' => 'GW',
                'Alpha3' => 'GNB',
                'En' => 'Guinea-Bissau',
                'Ru' => 'Гвинея-Бисау',
            ],
            [
                'Id' => 328,
                'Alpha2' => 'GY',
                'Alpha3' => 'GUY',
                'En' => 'Guyana',
                'Ru' => 'Гайана',
            ],
            [
                'Id' => 332,
                'Alpha2' => 'HT',
                'Alpha3' => 'HTI',
                'En' => 'Haiti',
                'Ru' => 'Гаити',
            ],
            [
                'Id' => 340,
                'Alpha2' => 'HN',
                'Alpha3' => 'HND',
                'En' => 'Honduras',
                'Ru' => 'Гондурас',
            ],
            [
                'Id' => 348,
                'Alpha2' => 'HU',
                'Alpha3' => 'HUN',
                'En' => 'Hungary',
                'Ru' => 'Венгрия',
            ],
            [
                'Id' => 352,
                'Alpha2' => 'IS',
                'Alpha3' => 'ISL',
                'En' => 'Iceland',
                'Ru' => 'Исландия',
            ],
            [
                'Id' => 356,
                'Alpha2' => 'IN',
                'Alpha3' => 'IND',
                'En' => 'India',
                'Ru' => 'Индия',
            ],
            [
                'Id' => 360,
                'Alpha2' => 'ID',
                'Alpha3' => 'IDN',
                'En' => 'Indonesia',
                'Ru' => 'Индонезия',
            ],
            [
                'Id' => 364,
                'Alpha2' => 'IR',
                'Alpha3' => 'IRN',
                'En' => 'Iran (Islamic Republic of]',
                'Ru' => 'Иран',
            ],
            [
                'Id' => 368,
                'Alpha2' => 'IQ',
                'Alpha3' => 'IRQ',
                'En' => 'Iraq',
                'Ru' => 'Ирак',
            ],
            [
                'Id' => 372,
                'Alpha2' => 'IE',
                'Alpha3' => 'IRL',
                'En' => 'Ireland',
                'Ru' => 'Ирландия',
            ],
            [
                'Id' => 376,
                'Alpha2' => 'IL',
                'Alpha3' => 'ISR',
                'En' => 'Israel',
                'Ru' => 'Израиль',
            ],
            [
                'Id' => 380,
                'Alpha2' => 'IT',
                'Alpha3' => 'ITA',
                'En' => 'Italy',
                'Ru' => 'Италия',
            ],
            [
                'Id' => 388,
                'Alpha2' => 'JM',
                'Alpha3' => 'JAM',
                'En' => 'Jamaica',
                'Ru' => 'Ямайка',
            ],
            [
                'Id' => 392,
                'Alpha2' => 'JP',
                'Alpha3' => 'JPN',
                'En' => 'Japan',
                'Ru' => 'Япония',
            ],
            [
                'Id' => 400,
                'Alpha2' => 'JO',
                'Alpha3' => 'JOR',
                'En' => 'Jordan',
                'Ru' => 'Иордания',
            ],
            [
                'Id' => 398,
                'Alpha2' => 'KZ',
                'Alpha3' => 'KAZ',
                'En' => 'Kazakhstan',
                'Ru' => 'Казахстан',
            ],
            [
                'Id' => 404,
                'Alpha2' => 'KE',
                'Alpha3' => 'KEN',
                'En' => 'Kenya',
                'Ru' => 'Кения',
            ],
            [
                'Id' => 296,
                'Alpha2' => 'KI',
                'Alpha3' => 'KIR',
                'En' => 'Kiribati',
                'Ru' => 'Кирибати',
            ],
            [
                'Id' => 408,
                'Alpha2' => 'KP',
                'Alpha3' => 'PRK',
                'En' => 'Korea (Democratic People\'s Republic of]',
                'Ru' => 'КНДР (Корейская Народно-Демократическая Республика]',
            ],
            [
                'Id' => 410,
                'Alpha2' => 'KR',
                'Alpha3' => 'KOR',
                'En' => 'Korea, Republic of',
                'Ru' => 'Республика Корея',
            ],
            [
                'Id' => 414,
                'Alpha2' => 'KW',
                'Alpha3' => 'KWT',
                'En' => 'Kuwait',
                'Ru' => 'Кувейт',
            ],
            [
                'Id' => 417,
                'Alpha2' => 'KG',
                'Alpha3' => 'KGZ',
                'En' => 'Kyrgyzstan',
                'Ru' => 'Киргизия',
            ],
            [
                'Id' => 418,
                'Alpha2' => 'LA',
                'Alpha3' => 'LAO',
                'En' => 'Lao People\'s Democratic Republic',
                'Ru' => 'Лаос',
            ],
            [
                'Id' => 428,
                'Alpha2' => 'LV',
                'Alpha3' => 'LVA',
                'En' => 'Latvia',
                'Ru' => 'Латвия',
            ],
            [
                'Id' => 422,
                'Alpha2' => 'LB',
                'Alpha3' => 'LBN',
                'En' => 'Lebanon',
                'Ru' => 'Ливан',
            ],
            [
                'Id' => 426,
                'Alpha2' => 'LS',
                'Alpha3' => 'LSO',
                'En' => 'Lesotho',
                'Ru' => 'Лесото',
            ],
            [
                'Id' => 430,
                'Alpha2' => 'LR',
                'Alpha3' => 'LBR',
                'En' => 'Liberia',
                'Ru' => 'Либерия',
            ],
            [
                'Id' => 434,
                'Alpha2' => 'LY',
                'Alpha3' => 'LBY',
                'En' => 'Libya',
                'Ru' => 'Ливия',
            ],
            [
                'Id' => 438,
                'Alpha2' => 'LI',
                'Alpha3' => 'LIE',
                'En' => 'Liechtenstein',
                'Ru' => 'Лихтенштейн',
            ],
            [
                'Id' => 440,
                'Alpha2' => 'LT',
                'Alpha3' => 'LTU',
                'En' => 'Lithuania',
                'Ru' => 'Литва',
            ],
            [
                'Id' => 442,
                'Alpha2' => 'LU',
                'Alpha3' => 'LUX',
                'En' => 'Luxembourg',
                'Ru' => 'Люксембург',
            ],
            [
                'Id' => 450,
                'Alpha2' => 'MG',
                'Alpha3' => 'MDG',
                'En' => 'Madagascar',
                'Ru' => 'Мадагаскар',
            ],
            [
                'Id' => 454,
                'Alpha2' => 'MW',
                'Alpha3' => 'MWI',
                'En' => 'Malawi',
                'Ru' => 'Малави',
            ],
            [
                'Id' => 458,
                'Alpha2' => 'MY',
                'Alpha3' => 'MYS',
                'En' => 'Malaysia',
                'Ru' => 'Малайзия',
            ],
            [
                'Id' => 462,
                'Alpha2' => 'MV',
                'Alpha3' => 'MDV',
                'En' => 'Maldives',
                'Ru' => 'Мальдивы',
            ],
            [
                'Id' => 466,
                'Alpha2' => 'ML',
                'Alpha3' => 'MLI',
                'En' => 'Mali',
                'Ru' => 'Мали',
            ],
            [
                'Id' => 470,
                'Alpha2' => 'MT',
                'Alpha3' => 'MLT',
                'En' => 'Malta',
                'Ru' => 'Мальта',
            ],
            [
                'Id' => 584,
                'Alpha2' => 'MH',
                'Alpha3' => 'MHL',
                'En' => 'Marshall Islands',
                'Ru' => 'Маршалловы Острова',
            ],
            [
                'Id' => 478,
                'Alpha2' => 'MR',
                'Alpha3' => 'MRT',
                'En' => 'Mauritania',
                'Ru' => 'Мавритания',
            ],
            [
                'Id' => 480,
                'Alpha2' => 'MU',
                'Alpha3' => 'MUS',
                'En' => 'Mauritius',
                'Ru' => 'Маврикий',
            ],
            [
                'Id' => 484,
                'Alpha2' => 'MX',
                'Alpha3' => 'MEX',
                'En' => 'Mexico',
                'Ru' => 'Мексика',
            ],
            [
                'Id' => 583,
                'Alpha2' => 'FM',
                'Alpha3' => 'FSM',
                'En' => 'Micronesia (Federated States of]',
                'Ru' => 'Микронезия',
            ],
            [
                'Id' => 498,
                'Alpha2' => 'MD',
                'Alpha3' => 'MDA',
                'En' => 'Moldova, Republic of',
                'Ru' => 'Молдавия',
            ],
            [
                'Id' => 492,
                'Alpha2' => 'MC',
                'Alpha3' => 'MCO',
                'En' => 'Monaco',
                'Ru' => 'Монако',
            ],
            [
                'Id' => 496,
                'Alpha2' => 'MN',
                'Alpha3' => 'MNG',
                'En' => 'Mongolia',
                'Ru' => 'Монголия',
            ],
            [
                'Id' => 499,
                'Alpha2' => 'ME',
                'Alpha3' => 'MNE',
                'En' => 'Montenegro',
                'Ru' => 'Черногория',
            ],
            [
                'Id' => 504,
                'Alpha2' => 'MA',
                'Alpha3' => 'MAR',
                'En' => 'Morocco',
                'Ru' => 'Марокко',
            ],
            [
                'Id' => 508,
                'Alpha2' => 'MZ',
                'Alpha3' => 'MOZ',
                'En' => 'Mozambique',
                'Ru' => 'Мозамбик',
            ],
            [
                'Id' => 104,
                'Alpha2' => 'MM',
                'Alpha3' => 'MMR',
                'En' => 'Myanmar',
                'Ru' => 'Мьянма',
            ],
            [
                'Id' => 516,
                'Alpha2' => 'NA',
                'Alpha3' => 'NAM',
                'En' => 'Namibia',
                'Ru' => 'Намибия',
            ],
            [
                'Id' => 520,
                'Alpha2' => 'NR',
                'Alpha3' => 'NRU',
                'En' => 'Nauru',
                'Ru' => 'Науру',
            ],
            [
                'Id' => 524,
                'Alpha2' => 'NP',
                'Alpha3' => 'NPL',
                'En' => 'Nepal',
                'Ru' => 'Непал',
            ],
            [
                'Id' => 528,
                'Alpha2' => 'NL',
                'Alpha3' => 'NLD',
                'En' => 'Netherlands',
                'Ru' => 'Нидерланды',
            ],
            [
                'Id' => 554,
                'Alpha2' => 'NZ',
                'Alpha3' => 'NZL',
                'En' => 'New Zealand',
                'Ru' => 'Новая Зеландия',
            ],
            [
                'Id' => 558,
                'Alpha2' => 'NI',
                'Alpha3' => 'NIC',
                'En' => 'Nicaragua',
                'Ru' => 'Никарагуа',
            ],
            [
                'Id' => 562,
                'Alpha2' => 'NE',
                'Alpha3' => 'NER',
                'En' => 'Niger',
                'Ru' => 'Нигер',
            ],
            [
                'Id' => 566,
                'Alpha2' => 'NG',
                'Alpha3' => 'NGA',
                'En' => 'Nigeria',
                'Ru' => 'Нигерия',
            ],
            [
                'Id' => 807,
                'Alpha2' => 'MK',
                'Alpha3' => 'MKD',
                'En' => 'North Macedonia',
                'Ru' => 'Северная Македония',
            ],
            [
                'Id' => 578,
                'Alpha2' => 'NO',
                'Alpha3' => 'NOR',
                'En' => 'Norway',
                'Ru' => 'Норвегия',
            ],
            [
                'Id' => 512,
                'Alpha2' => 'OM',
                'Alpha3' => 'OMN',
                'En' => 'Oman',
                'Ru' => 'Оман',
            ],
            [
                'Id' => 586,
                'Alpha2' => 'PK',
                'Alpha3' => 'PAK',
                'En' => 'Pakistan',
                'Ru' => 'Пакистан',
            ],
            [
                'Id' => 585,
                'Alpha2' => 'PW',
                'Alpha3' => 'PLW',
                'En' => 'Palau',
                'Ru' => 'Палау',
            ],
            [
                'Id' => 591,
                'Alpha2' => 'PA',
                'Alpha3' => 'PAN',
                'En' => 'Panama',
                'Ru' => 'Панама',
            ],
            [
                'Id' => 598,
                'Alpha2' => 'PG',
                'Alpha3' => 'PNG',
                'En' => 'Papua New Guinea',
                'Ru' => 'Папуа — Новая Гвинея',
            ],
            [
                'Id' => 600,
                'Alpha2' => 'PY',
                'Alpha3' => 'PRY',
                'En' => 'Paraguay',
                'Ru' => 'Парагвай',
            ],
            [
                'Id' => 604,
                'Alpha2' => 'PE',
                'Alpha3' => 'PER',
                'En' => 'Peru',
                'Ru' => 'Перу',
            ],
            [
                'Id' => 608,
                'Alpha2' => 'PH',
                'Alpha3' => 'PHL',
                'En' => 'Philippines',
                'Ru' => 'Филиппины',
            ],
            [
                'Id' => 616,
                'Alpha2' => 'PL',
                'Alpha3' => 'POL',
                'En' => 'Poland',
                'Ru' => 'Польша',
            ],
            [
                'Id' => 620,
                'Alpha2' => 'PT',
                'Alpha3' => 'PRT',
                'En' => 'Portugal',
                'Ru' => 'Португалия',
            ],
            [
                'Id' => 634,
                'Alpha2' => 'QA',
                'Alpha3' => 'QAT',
                'En' => 'Qatar',
                'Ru' => 'Катар',
            ],
            [
                'Id' => 642,
                'Alpha2' => 'RO',
                'Alpha3' => 'ROU',
                'En' => 'Romania',
                'Ru' => 'Румыния',
            ],
            [
                'Id' => 643,
                'Alpha2' => 'RU',
                'Alpha3' => 'RUS',
                'En' => 'Russian Federation',
                'Ru' => 'Россия',
            ],
            [
                'Id' => 646,
                'Alpha2' => 'RW',
                'Alpha3' => 'RWA',
                'En' => 'Rwanda',
                'Ru' => 'Руанда',
            ],
            [
                'Id' => 659,
                'Alpha2' => 'KN',
                'Alpha3' => 'KNA',
                'En' => 'Saint Kitts and Nevis',
                'Ru' => 'Сент-Китс и Невис',
            ],
            [
                'Id' => 662,
                'Alpha2' => 'LC',
                'Alpha3' => 'LCA',
                'En' => 'Saint Lucia',
                'Ru' => 'Сент-Люсия',
            ],
            [
                'Id' => 670,
                'Alpha2' => 'VC',
                'Alpha3' => 'VCT',
                'En' => 'Saint Vincent and the Grenadines',
                'Ru' => 'Сент-Винсент и Гренадины',
            ],
            [
                'Id' => 882,
                'Alpha2' => 'WS',
                'Alpha3' => 'WSM',
                'En' => 'Samoa',
                'Ru' => 'Самоа',
            ],
            [
                'Id' => 674,
                'Alpha2' => 'SM',
                'Alpha3' => 'SMR',
                'En' => 'San Marino',
                'Ru' => 'Сан-Марино',
            ],
            [
                'Id' => 678,
                'Alpha2' => 'ST',
                'Alpha3' => 'STP',
                'En' => 'Sao Tome and Principe',
                'Ru' => 'Сан-Томе и Принсипи',
            ],
            [
                'Id' => 682,
                'Alpha2' => 'SA',
                'Alpha3' => 'SAU',
                'En' => 'Saudi Arabia',
                'Ru' => 'Саудовская Аравия',
            ],
            [
                'Id' => 686,
                'Alpha2' => 'SN',
                'Alpha3' => 'SEN',
                'En' => 'Senegal',
                'Ru' => 'Сенегал',
            ],
            [
                'Id' => 688,
                'Alpha2' => 'RS',
                'Alpha3' => 'SRB',
                'En' => 'Serbia',
                'Ru' => 'Сербия',
            ],
            [
                'Id' => 690,
                'Alpha2' => 'SC',
                'Alpha3' => 'SYC',
                'En' => 'Seychelles',
                'Ru' => 'Сейшельские Острова',
            ],
            [
                'Id' => 694,
                'Alpha2' => 'SL',
                'Alpha3' => 'SLE',
                'En' => 'Sierra Leone',
                'Ru' => 'Сьерра-Леоне',
            ],
            [
                'Id' => 702,
                'Alpha2' => 'SG',
                'Alpha3' => 'SGP',
                'En' => 'Singapore',
                'Ru' => 'Сингапур',
            ],
            [
                'Id' => 703,
                'Alpha2' => 'SK',
                'Alpha3' => 'SVK',
                'En' => 'Slovakia',
                'Ru' => 'Словакия',
            ],
            [
                'Id' => 705,
                'Alpha2' => 'SI',
                'Alpha3' => 'SVN',
                'En' => 'Slovenia',
                'Ru' => 'Словения',
            ],
            [
                'Id' => 90,
                'Alpha2' => 'SB',
                'Alpha3' => 'SLB',
                'En' => 'Solomon Islands',
                'Ru' => 'Соломоновы Острова',
            ],
            [
                'Id' => 706,
                'Alpha2' => 'SO',
                'Alpha3' => 'SOM',
                'En' => 'Somalia',
                'Ru' => 'Сомали',
            ],
            [
                'Id' => 710,
                'Alpha2' => 'ZA',
                'Alpha3' => 'ZAF',
                'En' => 'South Africa',
                'Ru' => 'ЮАР',
            ],
            [
                'Id' => 728,
                'Alpha2' => 'SS',
                'Alpha3' => 'SSD',
                'En' => 'South Sudan',
                'Ru' => 'Южный Судан',
            ],
            [
                'Id' => 724,
                'Alpha2' => 'ES',
                'Alpha3' => 'ESP',
                'En' => 'Spain',
                'Ru' => 'Испания',
            ],
            [
                'Id' => 144,
                'Alpha2' => 'LK',
                'Alpha3' => 'LKA',
                'En' => 'Sri Lanka',
                'Ru' => 'Шри-Ланка',
            ],
            [
                'Id' => 729,
                'Alpha2' => 'SD',
                'Alpha3' => 'SDN',
                'En' => 'Sudan',
                'Ru' => 'Судан',
            ],
            [
                'Id' => 740,
                'Alpha2' => 'SR',
                'Alpha3' => 'SUR',
                'En' => 'Suriname',
                'Ru' => 'Суринам',
            ],
            [
                'Id' => 752,
                'Alpha2' => 'SE',
                'Alpha3' => 'SWE',
                'En' => 'Sweden',
                'Ru' => 'Швеция',
            ],
            [
                'Id' => 756,
                'Alpha2' => 'CH',
                'Alpha3' => 'CHE',
                'En' => 'Switzerland',
                'Ru' => 'Швейцария',
            ],
            [
                'Id' => 760,
                'Alpha2' => 'SY',
                'Alpha3' => 'SYR',
                'En' => 'Syrian Arab Republic',
                'Ru' => 'Сирия',
            ],
            [
                'Id' => 762,
                'Alpha2' => 'TJ',
                'Alpha3' => 'TJK',
                'En' => 'Tajikistan',
                'Ru' => 'Таджикистан',
            ],
            [
                'Id' => 834,
                'Alpha2' => 'TZ',
                'Alpha3' => 'TZA',
                'En' => 'Tanzania, United Republic of',
                'Ru' => 'Танзания',
            ],
            [
                'Id' => 764,
                'Alpha2' => 'TH',
                'Alpha3' => 'THA',
                'En' => 'Thailand',
                'Ru' => 'Таиланд',
            ],
            [
                'Id' => 626,
                'Alpha2' => 'TL',
                'Alpha3' => 'TLS',
                'En' => 'Timor-Leste',
                'Ru' => 'Восточный Тимор',
            ],
            [
                'Id' => 768,
                'Alpha2' => 'TG',
                'Alpha3' => 'TGO',
                'En' => 'Togo',
                'Ru' => 'Того',
            ],
            [
                'Id' => 776,
                'Alpha2' => 'TO',
                'Alpha3' => 'TON',
                'En' => 'Tonga',
                'Ru' => 'Тонга',
            ],
            [
                'Id' => 780,
                'Alpha2' => 'TT',
                'Alpha3' => 'TTO',
                'En' => 'Trinidad and Tobago',
                'Ru' => 'Тринидад и Тобаго',
            ],
            [
                'Id' => 788,
                'Alpha2' => 'TN',
                'Alpha3' => 'TUN',
                'En' => 'Tunisia',
                'Ru' => 'Тунис',
            ],
            [
                'Id' => 792,
                'Alpha2' => 'TR',
                'Alpha3' => 'TUR',
                'En' => 'Turkey',
                'Ru' => 'Турция',
            ],
            [
                'Id' => 795,
                'Alpha2' => 'TM',
                'Alpha3' => 'TKM',
                'En' => 'Turkmenistan',
                'Ru' => 'Туркмения',
            ],
            [
                'Id' => 798,
                'Alpha2' => 'TV',
                'Alpha3' => 'TUV',
                'En' => 'Tuvalu',
                'Ru' => 'Тувалу',
            ],
            [
                'Id' => 800,
                'Alpha2' => 'UG',
                'Alpha3' => 'UGA',
                'En' => 'Uganda',
                'Ru' => 'Уганда',
            ],
            [
                'Id' => 804,
                'Alpha2' => 'UA',
                'Alpha3' => 'UKR',
                'En' => 'Ukraine',
                'Ru' => 'Украина',
            ],
            [
                'Id' => 784,
                'Alpha2' => 'AE',
                'Alpha3' => 'ARE',
                'En' => 'United Arab Emirates',
                'Ru' => 'ОАЭ',
            ],
            [
                'Id' => 826,
                'Alpha2' => 'GB',
                'Alpha3' => 'GBR',
                'En' => 'United Kingdom of Great Britain and Northern Ireland',
                'Ru' => 'Великобритания',
            ],
            [
                'Id' => 840,
                'Alpha2' => 'US',
                'Alpha3' => 'USA',
                'En' => 'United States of America',
                'Ru' => 'США',
            ],
            [
                'Id' => 858,
                'Alpha2' => 'UY',
                'Alpha3' => 'URY',
                'En' => 'Uruguay',
                'Ru' => 'Уругвай',
            ],
            [
                'Id' => 860,
                'Alpha2' => 'UZ',
                'Alpha3' => 'UZB',
                'En' => 'Uzbekistan',
                'Ru' => 'Узбекистан',
            ],
            [
                'Id' => 548,
                'Alpha2' => 'VU',
                'Alpha3' => 'VUT',
                'En' => 'Vanuatu',
                'Ru' => 'Вануату',
            ],
            [
                'Id' => 862,
                'Alpha2' => 'VE',
                'Alpha3' => 'VEN',
                'En' => 'Venezuela (Bolivarian Republic of]',
                'Ru' => 'Венесуэла',
            ],
            [
                'Id' => 704,
                'Alpha2' => 'VN',
                'Alpha3' => 'VNM',
                'En' => 'Viet Nam',
                'Ru' => 'Вьетнам',
            ],
            [
                'Id' => 887,
                'Alpha2' => 'YE',
                'Alpha3' => 'YEM',
                'En' => 'Yemen',
                'Ru' => 'Йемен',
            ],
            [
                'Id' => 894,
                'Alpha2' => 'ZM',
                'Alpha3' => 'ZMB',
                'En' => 'Zambia',
                'Ru' => 'Замбия',
            ],
            [
                'Id' => 716,
                'Alpha2' => 'ZW',
                'Alpha3' => 'ZWE',
                'En' => 'Zimbabwe',
                'Ru' => 'Зимбабве',
            ],
        ];
    }

}
