<?php


namespace app\models\sms\tables;


use yii\db\ActiveRecord;
/**
 * @property string $phone
 * @property string $code
 * @property int $confirm
 * @property int $id
*/
class Sms extends ActiveRecord
{
    public static function tableName()
    {
        return 'sms'; // TODO: Change the autogenerated stub
    }

    public function getVia()
    {
        return $this->hasMany(SmsOrders::className(),['sms_id'=>'id']);
    }
}