<?php


namespace app\models\antifraud\tables;


use yii\db\ActiveRecord;

/**
 * @property integer $bin
 * @property string $country
 * @property string $payment_system
 * @property integer $id
 */
class AFBinBanks extends ActiveRecord
{
    public static function tableName()
    {
        return 'antifraud_bin_banks'; // TODO: Change the autogenerated stub
    }
}