<?php


namespace app\models\antifraud\tables;


use yii\db\ActiveRecord;

/**
 * @property integer $id
 * @property string $card_hash
 * @property integer ip_num
 * @property int $finger_print_id
 * @property AFFingerPrit $transaction
 */
class AFCardIps extends ActiveRecord
{
    public static function tableName()
    {
        return 'antifraud_card_ips'; // TODO: Change the autogenerated stub
    }

    public function getTransaction()
    {
        return $this->hasOne(AFFingerPrit::className(), ['id' => 'finger_print_id']);
    }
}