<?php


namespace app\models\antifraud\tables;


use yii\db\ActiveRecord;


/**
 * @property integer $id;
 * @property string $user_hash;
 * @property string $country
 * @property string $finger_print_id
*/
class AFCountry extends ActiveRecord
{
    public static function tableName()
    {
        return 'antifraud_country'; // TODO: Change the autogenerated stub
    }
}