<?php


namespace app\models\antifraud\tables;


use yii\db\ActiveRecord;

/**
 * @property string user_hash
 * @property string transaction_id
 * @property float weight
 * @property integer id
 * @property boolean status
 * @property AFStat[] stats
 * @property AFCards $card
 */
class AFFingerPrit extends ActiveRecord
{
    public static function tableName()
    {
        return 'antifraud_finger_print'; // TODO: Change the autogenerated stub
    }

    public function getIps()
    {
        return $this->hasMany(AFIps::className(), ['finger_print_id' => 'id']);
    }

    public function user_updated_page(int $trans_id = null, string $user_hash = null): bool
    {
        $record = AFFingerPrit::find()
            ->where(['transaction_id' => $trans_id, 'user_hash' => $user_hash])
            ->exists();
        return $record;
    }

    public function getStats(){
        return $this->hasMany(AFStat::className(), ['finger_print_id'=>'id']);
    }

    public function getCard(){
        return $this->hasOne(AFCards::className(), ['finger_print_id'=>'id']);
    }
}