<?php


namespace app\models\antifraud\tables;


use yii\db\ActiveRecord;
use yii\helpers\VarDumper;

/**
 * @property  string $user_hash
 * @property integer $ip_number
 * @property bool is_black
 *@property string $finger_print_id
 * @property AFCards $card_by_transaction
 * @property AFFingerPrit $transaction
*/
class AFIps extends ActiveRecord
{
    public static function tableName()
    {
        return 'antifraud_ip'; // TODO: Change the autogenerated stub
    }
//
    public function getTransaction(){
        return $this->hasOne(AFFingerPrit::className(), ['id'=>'finger_print_id'])->with('card');
    }


}