<?php


namespace app\models\antifraud\tables;


use yii\data\ActiveDataProvider;
use yii\data\ArrayDataProvider;
use yii\db\ActiveRecord;

/**
 * @property string $rule
 * @property string $description
 * @property string $rule_title
 * @proretry string $critical_value
 * @property int successCount
 * @property int failCount
 * @property int countStat
 *
*/
class AFRuleInfo extends ActiveRecord
{
    public static function tableName()
    {
        return 'antifraud_rule_info'; // TODO: Change the autogenerated stub
    }

    public function active_provider( $page){
        $list = self::find()->select('*');
        return new ActiveDataProvider([
            'query'=>$list,
            'sort' => false,
            'pagination' => [
                'pageSize' => 10,
                'page' => $page,
//                'totalCount' => count($list)
            ]
        ]);
    }

    public function getSuccess_count(){
        return $this->hasMany(AFStat::className(), ['rule'=>'rule'])
            ->andWhere(['antifraud_stat.success'=>true])
            ->count();
    }

    public function getFail_count(){
        return $this->hasMany(AFStat::className(), ['rule'=>'rule'])
            ->andWhere(['antifraud_stat.success'=>false])
            ->count();
    }

    public function getAll_count(){
        return $this->hasMany(AFStat::className(), ['rule'=>'rule'])
            ->count();
    }
}