<?php


namespace app\models\antifraud\tables;


use yii\db\ActiveRecord;
/**
 * @property int $id
 * @property string $key
 * @property string $value
*/
class AFSettings extends ActiveRecord
{
    public static function tableName()
    {
        return 'antifraud_settings'; // TODO: Change the autogenerated stub
    }
}