<?php


namespace app\models\antifraud\tables;


use yii\db\ActiveRecord;

/**
 * @property integer $id
 * @property string $finger_print_id - для связи таблиц
 * @property string $rule
 * @property boolean $success;
 * @property float $current_weight;
 * @property AFRuleInfo $rule_info
*/
class AFStat extends ActiveRecord
{
    public static function tableName()
    {
        return 'antifraud_stat'; // TODO: Change the autogenerated stub
    }

    public function getRule_info(){
        return $this->hasOne(AFRuleInfo::className(), ['rule'=>'rule']);
    }
}