<?php


namespace app\models\mfo;


use app\models\payonline\Partner;
use yii\db\ActiveRecord;

/**
 * @property integer $id
 * @property integer $partner_id
 * @property integer $payment
 * @property integer $repayment
 * @property string  $email
 * @property integer $last_send
 */
class DistributionReports extends ActiveRecord
{
    public function rules()
    {
        return [
            [['partner_id', 'payment', 'repayment', 'last_send'], 'integer'],
            [['email'], '\app\models\EmailListValidator'],
            [['partner_id', 'email'], 'required'],
        ];
    }

    public static function tableName()
    {
        return 'distribution_reports'; // TODO: Change the autogenerated stub
    }

    public function getPartner(){
        return $this->hasOne(Partner::className(),['ID'=>'partner_id']);
    }

    /**
     * возвращает партнеров которым можно сделать рассылку.
     * @return DistributionReports[]
    */
    public function validPartners(){
        return DistributionReports::find()
            ->where(['!=','partner_id', ''])
            ->andWhere(['!=', 'email', ''])
            ->all();
    }
}