style: none
template: CHANGELOG.tpl.md
info:
  title: CHANGELOG
  repository_url: https://git.vepay.cf/backend/cauri
options:
  commits:
    # filters:
    #   Type: []
  commit_groups:
    # title_maps: []
  header:
    pattern: "^(.*)$"
    pattern_maps:
      - Subject
  notes:
    keywords:
      - BREAKING CHANGE