<?php


namespace app\models\antifraud\partner;


use app\models\antifraud\tables\AFSettings;
use yii\base\Model;
use yii\helpers\VarDumper;

class RefundModel extends Model
{
    public $block_email_for_antifraud_refund;

    public function rules()
    {
        return [
            ['block_email_for_antifraud_refund', 'email']
        ]; // TODO: Change the autogenerated stub
    }

    public function save_block_email(){
        $record = AFSettings::find()->where(['key'=>'block_email_for_antifraud_refund'])->one();
        if ($record){
            $record->value = $this->block_email_for_antifraud_refund;
        }else{
            $record = new AFSettings();
            $record->key = 'block_email_for_antifraud_refund';
            $record->value = $this->block_email_for_antifraud_refund;
        }
        return $record->save();
    }
}